# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "glinda"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rschmukler"]
  s.date = "2012-10-14"
  s.description = "Toto, expanded"
  s.email = "ryan@slingingcode.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Glinda.gemspec",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/ext/ext.rb",
    "lib/glinda.rb",
    "spec/articles/1900-05-17-the-wonderful-wizard-of-oz.txt",
    "spec/articles/2001-01-01-two-thousand-and-one.txt",
    "spec/articles/2009-04-01-tilt-factor.txt",
    "spec/articles/2009-12-04-some-random-article.txt",
    "spec/articles/2009-12-11-the-dichotomy-of-design.txt",
    "spec/glinda_spec.rb",
    "spec/spec_helper.rb",
    "spec/templates/about.rhtml",
    "spec/templates/archives.rhtml",
    "spec/templates/article.rhtml",
    "spec/templates/feed.builder",
    "spec/templates/index.builder",
    "spec/templates/index.rhtml",
    "spec/templates/layout.rhtml",
    "spec/templates/repo.rhtml",
    "spec/templates/tags.rhtml"
  ]
  s.homepage = "http://github.com/rschmukler/glinda"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Toto, expanded"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdiscount>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_development_dependency(%q<fuubar>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemcutter>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 0"])
    else
      s.add_dependency(%q<rdiscount>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<fuubar>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemcutter>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdiscount>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<fuubar>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemcutter>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
  end
end

